name: com
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - images/bhushan_image.jpg



  fonts:
    - family: Bangers
      fonts:
        - asset: Font/Bangers-Regular.ttf
    - family: Permanent
      fonts:
        - asset: Font/PermanentMarker-Regular.ttf

    - family: Patrick
      fonts:
        - asset: images/PatrickHand-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

